version: '3.9'

services:
  redis:
    image: redis:7
    container_name: tss-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  node:
    build: .
    container_name: tss-node
    command: node server.js
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./data:/app/data
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: "redis://redis:6379"
      PORT : "3000"
      JWT_SECRET: "croissant"
    depends_on:
      - redis

  worker:
    build: .
    container_name: tss-worker
    command: node worker.js
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./data:/app/data
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=croissant
    depends_on:
      - redis

volumes:
  redis-data:


