version: '3.9'

services:
  redis:
    image: redis:7
    container_name: tss-redis
    ports:
      - "6379:6379"

  node:
    build: .
    container_name: tss-node
    command: node server.js
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    working_dir: /app
    ports:
      - "3216:3000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: tss-worker
    command: node worker.js
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads  # same uploads folder
    working_dir: /app
    depends_on:
      - redis


